### ISSUE TITLE
5-2. kuard-pod-health.yaml does not work

### ISSUE THREAD

**Issue by redhat-raptor** [kubernetes-up-and-running/examples#2]
I have the following conf saved in kuard-prod-health.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: gcr.io/kuar-demo/kuard-amd64:1
      name: kuard
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

However when I try to apply the conf:
`kubectl apply -f kuard-prod-health.yaml `

I get this error:

> The Pod "kuard" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
